/* <begin connected objects> */
/*
This file is auto generated by pgrx.

The ordering of items is not stable, it is driven by a dependency graph.
*/
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:61
-- cart_ext::cart_add_checkout_transaction_mark
CREATE  FUNCTION "cart_add_checkout_transaction_mark"(
	"stream_id" TEXT, /* &str */
	"instance_id" TEXT, /* &str */
	"transaction_type" TEXT, /* &str */
	"customer_id" TEXT, /* &str */
	"mark_status" TEXT, /* &str */
	"db" TEXT /* &str */
) RETURNS VOID /* core::result::Result<(), pgrx::spi::SpiError> */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'cart_add_checkout_transaction_mark_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:93
-- cart_ext::cart_add_price_transaction_mark
CREATE  FUNCTION "cart_add_price_transaction_mark"(
	"stream_id" TEXT, /* &str */
	"instance_id" TEXT, /* &str */
	"transaction_type" TEXT, /* &str */
	"seller_id" TEXT, /* &str */
	"mark_status" TEXT, /* &str */
	"db" TEXT /* &str */
) RETURNS VOID /* core::result::Result<(), pgrx::spi::SpiError> */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'cart_add_price_transaction_mark_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:77
-- cart_ext::cart_add_product_transaction_mark
CREATE  FUNCTION "cart_add_product_transaction_mark"(
	"stream_id" TEXT, /* &str */
	"instance_id" TEXT, /* &str */
	"transaction_type" TEXT, /* &str */
	"seller_id" TEXT, /* &str */
	"mark_status" TEXT, /* &str */
	"db" TEXT /* &str */
) RETURNS VOID /* core::result::Result<(), pgrx::spi::SpiError> */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'cart_add_product_transaction_mark_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:123
-- cart_ext::cart_listen_to_changes
CREATE  FUNCTION "cart_listen_to_changes"() RETURNS VOID /* core::result::Result<(), alloc::string::String> */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'cart_listen_to_changes_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:17
-- cart_ext::setup_cart
CREATE  FUNCTION "setup_cart"() RETURNS VOID /* core::result::Result<(), pgrx::spi::SpiError> */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'setup_cart_wrapper';
/* </end connected objects> */

