/* <begin connected objects> */
/*
This file is auto generated by pgrx.

The ordering of items is not stable, it is driven by a dependency graph.
*/
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:37
-- payment_ext::payment_add_checkout_transaction_mark
CREATE  FUNCTION "payment_add_checkout_transaction_mark"(
	"stream_id" TEXT, /* &str */
	"instance_id" TEXT, /* &str */
	"transaction_type" TEXT, /* &str */
	"customer_id" TEXT, /* &str */
	"mark_status" TEXT, /* &str */
	"db" TEXT /* &str */
) RETURNS VOID /* core::result::Result<(), pgrx::spi::SpiError> */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'payment_add_checkout_transaction_mark_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:70
-- payment_ext::payment_listen_to_changes
CREATE  FUNCTION "payment_listen_to_changes"() RETURNS VOID /* core::result::Result<(), alloc::string::String> */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'payment_listen_to_changes_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:17
-- payment_ext::setup_payment
CREATE  FUNCTION "setup_payment"() RETURNS VOID /* core::result::Result<(), pgrx::spi::SpiError> */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'setup_payment_wrapper';
/* </end connected objects> */

