/* <begin connected objects> */
/*
This file is auto generated by pgrx.

The ordering of items is not stable, it is driven by a dependency graph.
*/
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:30
-- shipment_ext::setup_shipment
CREATE  FUNCTION "setup_shipment"() RETURNS VOID /* core::result::Result<(), pgrx::spi::SpiError> */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'setup_shipment_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:51
-- shipment_ext::shipment_add_checkout_transaction_mark
CREATE  FUNCTION "shipment_add_checkout_transaction_mark"(
	"stream_id" TEXT, /* &str */
	"instance_id" TEXT, /* &str */
	"transaction_type" TEXT, /* &str */
	"customer_id" TEXT, /* &str */
	"mark_status" TEXT, /* &str */
	"db" TEXT /* &str */
) RETURNS VOID /* core::result::Result<(), pgrx::spi::SpiError> */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'shipment_add_checkout_transaction_mark_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:72
-- shipment_ext::shipment_listen_to_changes
CREATE  FUNCTION "shipment_listen_to_changes"() RETURNS VOID /* core::result::Result<(), alloc::string::String> */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'shipment_listen_to_changes_wrapper';
/* </end connected objects> */

